/* L9_META
 * layer: api
 * role: seo_bot_engine
 * status: active
 */

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * L9 SEO Bot - Reporting Query Gateway API (ADR-0015)
 *
 * The preferred way for humans and agents to reach SQL. A caller names a
 * registered view and passes validated filters; the gateway compiles it, audits
 * it, and runs it read-only with a per-audience statement timeout.
 *
 * Why a gateway rather than a database socket per consumer:
 *   - one central audit log, written before the query runs;
 *   - a view allow-list and a per-audience column projection;
 *   - parameter validation and row limits enforced in one place;
 *   - no arbitrary SQL generated by an LLM.
 *
 * A direct psql session for an operator remains legitimate (see
 * scripts/reporting/provision-roles.sql); this route is what everything
 * automated should use.
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import type { FastifyInstance } from "fastify";
import { createModuleLogger } from "../core/logger.js";
import { ReportingQueryError, type ReportingQueryRequest } from "../reporting/query-compiler.js";
import { executeReportingQuery } from "../reporting/query-gateway.js";
import { getRefreshStatus } from "../reporting/refresh.js";
import { listReportingViews } from "../reporting/views.js";

const logger = createModuleLogger("api:reporting");

interface QueryBody {
  view?: unknown;
  filters?: unknown;
  orderBy?: unknown;
  limit?: unknown;
}

export async function registerReportingRoutes(app: FastifyInstance): Promise<void> {
  /**
   * The registry, as the calling audience sees it. An agent asking what it may
   * query gets back only the views and columns it can actually reach — which is
   * also what makes named queries discoverable without a schema dump.
   */
  app.get("/api/reporting/views", async (request, reply) => {
    const actor = request.reportingActor;
    if (!actor) return reply.status(401).send({ error: "unauthorized" });

    const views = listReportingViews(actor.audience).map((view) => ({
      name: view.name,
      description: view.description,
      columns: view.projections[actor.audience] ?? [],
      filters: Object.fromEntries(
        Object.entries(view.filters).map(([name, spec]) => [
          name,
          {
            kind: spec.kind,
            description: spec.description,
            ...(spec.kind === "enum" || spec.kind === "enumIn" ? { values: spec.values } : {}),
            ...("min" in spec ? { min: spec.min, max: spec.max } : {}),
          },
        ]),
      ),
      orderBy: Object.keys(view.orderBy),
      defaultOrderBy: view.defaultOrderBy,
      defaultLimit: view.defaultLimit,
      maxLimit: view.maxLimit,
    }));

    return { audience: actor.audience, views };
  });

  /**
   * Run one named query. The body selects a registry entry and supplies values;
   * it never supplies SQL, a column name, a relation, or an ORDER BY fragment.
   */
  app.post<{ Body: QueryBody }>("/api/reporting/query", async (request, reply) => {
    const actor = request.reportingActor;
    if (!actor) return reply.status(401).send({ error: "unauthorized" });

    const body = (request.body ?? {}) as QueryBody;
    const queryRequest: ReportingQueryRequest = {
      view: typeof body.view === "string" ? body.view : "",
      filters:
        body.filters && typeof body.filters === "object" && !Array.isArray(body.filters)
          ? (body.filters as Record<string, unknown>)
          : undefined,
      orderBy: typeof body.orderBy === "string" ? body.orderBy : undefined,
      limit: typeof body.limit === "number" ? body.limit : undefined,
    };

    if (body.filters !== undefined && queryRequest.filters === undefined) {
      return reply.status(400).send({ error: "filters must be an object" });
    }
    if (body.limit !== undefined && typeof body.limit !== "number") {
      return reply.status(400).send({ error: "limit must be a number" });
    }

    try {
      const result = await executeReportingQuery(queryRequest, actor);
      return {
        view: result.view,
        columns: result.columns,
        rows: result.rows,
        rowCount: result.rowCount,
        truncated: result.truncated,
        limit: result.limit,
        durationMs: result.durationMs,
      };
    } catch (error) {
      if (error instanceof ReportingQueryError) {
        // A rejected request is the registry doing its job; the message names
        // the allowed views/filters so the caller can correct itself.
        return reply.status(400).send({ error: error.message });
      }
      logger.error(
        { err: error instanceof Error ? error.message : String(error), view: queryRequest.view },
        "Reporting query failed",
      );
      return reply.status(500).send({ error: "reporting query failed" });
    }
  });

  /**
   * Freshness of the materialized layer. An answer drawn from a stale snapshot
   * is worse than no answer, so the snapshot's age is part of the contract.
   */
  app.get("/api/reporting/refresh-status", async (request, reply) => {
    const actor = request.reportingActor;
    if (!actor) return reply.status(401).send({ error: "unauthorized" });
    return { views: await getRefreshStatus() };
  });

  logger.info("Reporting gateway routes registered");
}
